# --- ビルドステージ ---
FROM oven/bun:1-alpine AS builder

WORKDIR /app

COPY package.json bun.lockb ./

# 本番用ライブラリをインストール
RUN bun install --frozen-lockfile --production


# --- 実行ステージ ---
FROM oven/bun:1-alpine AS runner

WORKDIR /app

ENV NODE_ENV=production

# 依存関係をコピー
COPY --from=builder /app/node_modules ./node_modules
# ソースコードをコピー
COPY . .

USER bun

# ポート公開
EXPOSE 3000

# 実行コマンド
CMD ["bun", "src/infrastructure/server/index.ts"]